### ISSUE TITLE
Misleading "minified" error, maybe this doesn't work in angular or non-react environments?

### ISSUE THREAD

**Issue by kchima** [auth0-community/auth0-editprofile-widget#6]
Hello,

I [and others](https://auth0.com/forum/t/edit-profile-widget-lock-v10/4158) have been getting this error when trying to follow the tutorial for this editprofile widget, even in non-minified environments:

Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
at invariant (http://127.0.0.1:3005/js/auth0-editprofile-widget.js:20252:15)

I find that this happens when it tries to invoke some react-specific code, registering a "react component". I am in an angular environment, so this seems incorrect. I figure the problem is that this is specifically for react environments, but that is not made super clear in the readme and probably should be (if my assumption is correct).

I think your widget is important- considering how important user metadata is to Auth0, there should be a simple widget to allow users to modify their preferences like the custom auth0 signup widget does.

Is there a working angular version anywhere, or do you have plans to modify this to work with Angular? I think it would be extremely useful for me, among others.

Thanks,
-Keith

**Comment by kchima** [comment]
Just following up; are there any plans to release a version compatible with Angular? I think it would be extraordinarily useful for those of us trying to incorporate Auth0. I'd imagine one of the first things people would want to do after adding auth is to add preferences. Thanks!

**Comment by beardaway** [comment]
Hey there!

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
